# Routes package
from .auth import create_auth_routes
from .psychics import create_psychic_routes
from .wallet import create_wallet_routes
from .questions import create_questions_routes
from .favorites import create_favorites_routes
from .tips import create_tips_routes
from .reviews import create_reviews_routes
from .chat import create_chat_routes
from .psychic_portal import create_psychic_portal_routes
from .admin import create_admin_routes
from .horoscope import create_horoscope_routes
from .messages import create_messages_routes
from .support import create_support_routes
from .applications import create_application_routes
from .notifications import create_notifications_routes
from .websocket import create_websocket_routes
from .payments import create_payment_routes
from .email import create_email_routes
from .storage import create_storage_routes
from .video import create_video_routes
from .push_notifications import create_push_notification_routes
